### ISSUE TITLE
[Question] Usage/reliability

### ISSUE THREAD

**Issue by nathanhosselton** [joshhunt/destinyPlumbing#3]
Sorry, for the question in an Issue.

I'm helping with [Raid Dad](https://www.raiddad.com) and we're interested in leveraging your work here. I assume Destiny Sets relies on this already, which I take as an indicator of it being plenty solid. But I don't want to overstep by using it for ourselves if this isn't your intention or if it could risk compromising the integrity of your service.

I figure that you wouldn't have put it out there if you didn't want others to utilize it, but I'd rather ask than assume.

**Comment by joshhunt** [comment]
👋 Hey, thanks for popping by!  

While I did originally create this for Destiny Sets, I've since leaned away from using destiny.plumbing there and instead consume the .content manifest directly in the users browser (wild, I know). 

I keep destiny.plumbing around as a resource to help people getting started with the Destiny data, with the intention that once you've done all the interesting parts, you can move onto the 'boring' bit and sort out manifest data :)

I'm happy for people to use this, but just a few things to keep in mind:

 - I don't rely on this any more for anything. Take that as a single of my priority for this :)
   - In saying that, destiny.plumbing now updates more reliably since I've stopped using it and publish only English :)
 - Be responsible with bandwidth - DestinyInventoryItemDefinition can be an absolute monster, especially if you're loading it client side. If cost starts to be an issue here, we can work on finding a solution :)

Another option to consider could be what DIM and DestinySets.com does - load the .content archive directly in the user's browser and cache it between visits. You can see how Destiny Sets does that here https://github.com/joshhunt/destinySets/blob/master/src/lib/definitions/index.js#L189

**Comment by nathanhosselton** [comment]
Thanks so much for all this info! Super helpful. And thank you for making destiny.plumbing; it will definitely be a valuable resource for us even without our consuming of it directly.
